---
title: "Notes Chapter 17"
author: "Semiramis Castro-Jaimes"
date: "17/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rlang)
library(lobstr)
```

We capture what we write with expr
```{r}
capture_it_expr <- function(x) {
  expr(x)
}

capture_it_expr(a + b + c )

```

We can capture the code passed to a function with enexpr:
```{r}
capture_it_enexpr <- function(x) {
  enexpr(x)
}

capture_it_enexpr(a + b + c )

```

Code is data. Expressions behave like lists and its first element is the function to be called
```{r}
f <- expr(f(x = 1, y = 2))
f[[1]]; f[[2]]
```

Code is a tree, the Abstract syntax tree (AST). A filled squared is a new branch; the rest are leaves
```{r}
lobstr::ast(f1(f2(a, b), f3(1, f4(2))))
```

The arithmetic operations are presented in prefix form
```{r}
lobstr::ast(1 + 2 * 3)
```

**Janine's cool example:**
```{r}
library(ggplot2)
plot_scatter <- function(data, x_col, y_col) {
  browser()
  x_col <- enquo(x_col)
  y_col <- enquo(y_col)
  ggplot(data, # normal r rules
    aes(!!x_col, !!y_col)) + # special r rules
    geom_point()
}

plot_scatter(mtcars, disp, mpg)

```

